# Generated by Django 5.2.6 on 2026-09-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0005_purchase"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="department",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="attendance",
            name="check_in",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attendance",
            name="check_out",
            field=models.TimeField(blank=True, null=True),
        ),
    ]